### ISSUE TITLE
Create ComputeNeighbors module

### ISSUE THREAD

**Issue by yifatdzigan** [eEcoLiDAR/eEcoLiDAR#10]
The Compute neighbors module will compute the neighbors in the environment point cloud for each target point cloud.

Input: environment Point Cloud (where we look for neighbors), targets Point Cloud 
Output: iterator of neighbors.

This module should output a bunch of neighborhoods as pointclouds. Each neigborhood consists of the points near a single target point. The idea is that we don't necessarily calculate the neighbors for each of the point in a pointcloud but only for certain target points (for instance some subsample). 

For large input point clouds, the list of neighborhoods and all their members can get very big memorywise. Therefor, we want to return an iterator instead (using python yield?). This way, we can load a complete pointcloud, calculate only a single neighborhood, calculate its features in another module, erase the neighborhood from memory and move on to the next.

Neighborhoods can either be calculated using knn criterium, or using a specific radius in either x,y or x,y,z space.

**Comment by komazsofi** [comment]
Most important to implement:
- [ ] closest point within a cylinder (kdTree build in 2D (x,y) and search the neighborhood points in 2D domain than go back in the 3D space)
- [ ] closest point within a sphere (3D search using x,,y,z)

**Comment by komazsofi** [comment]
Example code:  
```python
from scipy.spatial import cKDTree

sim_pcloud=np.array([[1,1],[2,4],[3,2],[5,1.5],[7,3],[10,1.25],[5,5],[2.5,8]])

radius=2.5
kdtree = cKDTree(sim_pcloud)
point_neighbours_rad = kdtree.query_ball_point(sim_pcloud, radius)

for i in range(len(sim_pcloud)):
    local_points_rad = sim_pcloud[point_neighbours_rad[i]]
    print(i)
    print(local_points_rad)

```

**Comment by bouweandela** [comment]
I recommend experimenting with setting
`scipy.spatial.cKDTree(points, compact_nodes=False, balanced_tree=False)`
to see if using an unbalanced tree improves performance.
Also note that the `query` method accepts a `n_jobs` parameter to query in parellel.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html
