### ISSUE TITLE
entropy_z is crashing

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#103]
Code:

```python
import argparse
import time
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument('path_of_laserchicken', help='The path of laserchicken')
parser.add_argument('input', help='absolute path of input point cloud')
parser.add_argument('target', help='target points as las file')
parser.add_argument('radius', help='radius of the volume')
parser.add_argument('output', help='absolute path of output point cloud')
args = parser.parse_args()

import sys
sys.path.insert(0, args.path_of_laserchicken)

from laserchicken import read_las
from laserchicken.keys import point
from laserchicken.volume_specification import InfiniteCylinder
from laserchicken.compute_neighbors import compute_neighborhoods
from laserchicken.feature_extractor import compute_features
from laserchicken.write_ply import write

print("------ Import is started ------")

pc = read_las.read(args.input)
target = read_las.read(args.target)

print(("Number of points: %s ") % (pc[point]['x']['data'].shape[0]))
print(("Number of points in target: %s ") % (target[point]['x']['data'].shape[0]))

print("------ Computing neighborhood is started ------")

start = time.time()
indices_cyl=compute_neighborhoods(pc, target, InfiniteCylinder(np.float(args.radius)))
end = time.time()
difftime=end - start
print(("build kd-tree: %f sec") % (difftime))

print("------ Feature calculation is started ------")

start1 = time.time()

compute_features(pc, indices_cyl, target, ['max_z','echo_ratio','eigenv_1', 'eigenv_2', 'eigenv_3','z_entropy',
'normal_vector_1','normal_vector_2','normal_vector_3','slope','pulse_penetration_ratio', 'density_absolute_mean','sigma_z'], InfiniteCylinder(np.float(args.radius)))

end1 = time.time()
difftime1=end1 - start1
print(("feature calc: %f sec") % (difftime1))

write(target,args.output)
```
Error:
Feature "z_entropy"Traceback (most recent call last):
 File "/data/GitHub/romulo/myPhD_escience_analysis/test_laserchicken//computefea_wtargets_cylinder.py", line 44, in <module>
   'normal_vector_1','normal_vector_2','normal_vector_3','slope','pulse_penetration_ratio', 'density_absolute_mean','sigma_z'], InfiniteCylinder(np.float(args.radius)))
 File "/data/GitHub/romulo/eEcoLiDAR/laserchicken/feature_extractor/__init__.py", line 72, in compute_features
   _add_or_update_feature(env_point_cloud, neighborhoods, target_point_cloud, extractor, volume, overwrite, kwargs)
 File "/data/GitHub/romulo/eEcoLiDAR/laserchicken/feature_extractor/__init__.py", line 97, in _add_or_update_feature
   target_index, volume)
 File "/data/GitHub/romulo/eEcoLiDAR/laserchicken/feature_extractor/entropy_feature_extractor.py", line 35, in extract
   data = np.histogram(z, bins=n_bins, range=(_z_min, _z_max), density=True)[0]
 File "/home/zsofi/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 721, in histogram
   raise ValueError('`bins` must be positive, when an integer')

**Comment by romulogoncalves** [comment]
You need to provide:
path_of_laserchicken, input, target, radius, output

**Comment by komazsofi** [comment]
python computefea_wtargets_cylinder.py D:/Koma/GitHub/eEcoLiDAR D:/Koma/DataProcess/OrigData/tile_209000_599000_1_1.las D:/Koma/DataProcess/OrigData/tile_209000_599000_1_1.las 1 D:/Koma/DataProcess/OrigData//tile_209000_599000_1_1_fea.ply

D:/Koma/GitHub/eEcoLiDAR -- path of laserchicken on the computer
D:/Koma/DataProcess/OrigData/tile_209000_599000_1_1.las : input las file
D:/Koma/DataProcess/OrigData/tile_209000_599000_1_1.las : target (in this case the same)
1 radius of the cylinder
D:/Koma/DataProcess/OrigData//tile_209000_599000_1_1_fea.ply absolute path of output

**Comment by romulogoncalves** [comment]
When z_min == z_max, the [extract function](https://github.com/eEcoLiDAR/eEcoLiDAR/blob/development/laserchicken/feature_extractor/entropy_feature_extractor.py) crashes due to division of zero:
```
def extract(self, source_pc, neighborhood, target_pc, target_index, volume_description):
    z = source_pc[keys.point]["z"]["data"][neighborhood]
    _z_min = np.min(z) if self.z_min is None else self.z_min
    _z_max = np.max(z) if self.z_max is None else self.z_max
   n_bins = int(np.ceil((_z_max - _z_min) / self.layer_thickness))     <------ This one
    data = np.histogram(z, bins=n_bins, range=(_z_min, _z_max), density=True)[0]
    entropy_func = np.vectorize(_x_log_2x)
        norm = np.sum(data)
        return -(entropy_func(data / norm)).sum()
```
