### ISSUE TITLE
Using python-plyfile: License issues

### ISSUE THREAD

**Issue by yifatdzigan** [eEcoLiDAR/eEcoLiDAR#14]
We may not use this dependency because of its GNU General Public License.
Instead - look for another reader/writer or write a new one.

**Comment by yifatdzigan** [comment]
We may not use this dependency because of its GNU General Public License.

**Comment by cwmeijer** [comment]
Other options are: 
- pymesh. This however has quite complicated installation instructions and is also quite a big project to have as a dependency
- [pyntcloud](https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/io/ply.py). This doesn't have an actual license but an UNLICENSE meaning that they sort of try to donate their code to the public domain. Legally I don't think their unlicense makes sense which leaves us in a weird position if we are to use their code (without an actual license). Their implementation might be an example for us of how to implement a ply file writer though.

**Comment by cwmeijer** [comment]
I decided to write my own tooling for this. The existing libraries either didn't have a compatible license or were lacking necessary features.
