### ISSUE TITLE
Create Sigma(z) feature extractor [1]

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#20]
ask Zsofi for the exact explanation 

1. fit a plane to the selected points within the neighborhood (within cylinder),
2. standard deviation of the residual of the points from the fitted plane (difference between model:plane and measurement:points)

All feature extractors need to implement the feature extractor interface from #19.
This feature is similar to: #35, #22

**Comment by komazsofi** [comment]
![](http://www.mdpi.com/remotesensing/remotesensing-04-01617/article_deploy/html/images/remotesensing-04-01617f5-1024.png) Zlinszky et al., 2012

**Comment by NicoRenaud** [comment]
@cwmeijer i ve started working on issue #35 if you need that
