### ISSUE TITLE
Create echo ratio feature extractor [3]

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#21]
ask Zsofi for the exact explanation

Echo ratio [%] = n3D / n2D * 100.0 where n3D is the number of points within a sphere and n2D is the number of points within a cylinder with the same radius.

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
Read section 3.1.1. https://pdfs.semanticscholar.org/c20a/8cd475c3222a3dba940494c0780daef631cc.pdf

**Comment by NicoRenaud** [comment]
We need to specify both the neighboors of the sphere and the cylinder. To do that I expect that the neighborhood argument in the extractor method contains a list of list: [[index_sphere],[index_cylinder]]. This conflicts with the general description of the feature extractor. But I don't see a way to solve that other than computing the neighborhood within the extractor.

**Comment by cwmeijer** [comment]
Indeed, the sphere part will have to be calculated within the feature extractor. This is a very different operation than searching the nearest neighbors in the entire environment cloud, because the sphere will be a subvolume of the infinite cylinder. We ca just loop through the points in the cylinder to see whether the point is also in the sphere. Creating a kdtree for this is not worth it I think. That would only help when searching many points.

It is probably a good idea to test whether the volume you're getting is a an InfiniteCylinder. If it's something else (for instance a Sphere), you won't be able to calculate this feature based on its neighbors alone. In this case it should raise some error.
