### ISSUE TITLE
create pulse penetration ratio feature extractor [2]

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#23]
ask Zsofi for the exact explanation

Ratio of number of points within a selected layer to all point within the cylinder. 
More possibilities to calculate: 
- [ ] ratio between ground, non ground
- [ ] ratio within specific height layer to total number of points (depends on #34)
- [ ] number of points above mean to total number of points

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
```python


```

**Comment by NicoRenaud** [comment]
Before I make a pull request, the ground points are labelled by a 2 in the raw classification right ?

**Comment by komazsofi** [comment]
yes 2 should be the ground points

**Comment by NicoRenaud** [comment]
thanks
