### ISSUE TITLE
create height statistics feature extractor

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#24]
ask Zsofi for the exact explanation

Calculate the 
- [ ] maximum, 
- [ ] minimum, 
- [ ] mean, 
- [ ] median, 
- [ ] standard deviation, 
- [ ] variance, 
- [ ] range (max-min), 
- [ ] median, 
- [ ] coefficient of variation 
of the given attribute (z) within the given neighborhood (cylinder).

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
Example code (where NormalizedZ== Z -- height attribute)

def general_statistics_descriptors(NormalizedZ):
    import scipy.stats.stats as stat
    mean_z=np.mean(NormalizedZ)
    median_z=np.median(NormalizedZ)
    var_z=np.var(NormalizedZ)
    std_z=np.std(NormalizedZ)
    coeffvar_z=np.std(NormalizedZ)/np.mean(NormalizedZ)
    skew_z=stat.skew(NormalizedZ)
    kurto_z=stat.kurtosis(NormalizedZ)
    max_z=np.percentile(NormalizedZ,98)
    return mean_z,median_z,var_z,std_z,coeffvar_z,skew_z,kurto_z,max_z
