### ISSUE TITLE
add percentiles feature extractor

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#25]
ask Zsofi for the exact explanation

Calculate the percentiles of the given attribute (z) within the given neighborhood (cylinder)

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
Example code: z_array is the z attribute (height)
Used python packages:
- import numpy as np
- from scipy import stats

       perc_10=stats.scoreatpercentile(z_array,10)
       perc_20=stats.scoreatpercentile(z_array,20)
       perc_30=stats.scoreatpercentile(z_array,30)
       perc_40=stats.scoreatpercentile(z_array,40)
       perc_50=stats.scoreatpercentile(z_array,50)
       perc_60=stats.scoreatpercentile(z_array,60)
       perc_70=stats.scoreatpercentile(z_array,70)
       perc_80=stats.scoreatpercentile(z_array,80)
       perc_90=stats.scoreatpercentile(z_array,90)

**Comment by cwmeijer** [comment]
Is the height you are referring to is the normalized height?

**Comment by komazsofi** [comment]
referring to normalized height

**Comment by NicoRenaud** [comment]
But we don't have the normalized height feature yet right ?

**Comment by cwmeijer** [comment]
No we don't but we'll just use the z value for now. We can use LAStools or whatever tool to replace the z values by normalized heights as work around. Also, I'm sitting 10 meters away from your desk so just talk to me ;-P

________________________________
