### ISSUE TITLE
point density feature extractor

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#27]
ask Zsofi for the exact explanation

Number of points within cylinder normalized by the area.

All feature extractors need to implement the feature extractor interface from #19.

**Comment by komazsofi** [comment]
Updated: 
- density: -- calculated within a cylinder
- volume: -- calculated within the cylinder within multiple heights layers

**Comment by romulogoncalves** [comment]
Covered by:
https://github.com/eEcoLiDAR/eEcoLiDAR/pull/60

**Comment by cwmeijer** [comment]
The extractor needs to use the feature extractor abstract base class.
