### ISSUE TITLE
create polygon filter

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#28]
Create a module or function in the filter module that filters pointclouds based on their x,y location and a given polygon.

Input should be a pointcloud in memory and output as well. For data format see https://github.com/eEcoLiDAR/eEcoLiDAR/blob/master/Data_Formats_README.md#internal-data-structure.

**Comment by romulogoncalves** [comment]
Covered by:
https://github.com/eEcoLiDAR/eEcoLiDAR/pull/46
