### ISSUE TITLE
Design or find intermediate file format

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#3]
This should support
- for each point x,y,z and an unlimited number of attributes (for instance normal x, normal y, normal z, class)
- each file contains 1 pointcloud 
- each pointcloud has an unlimited number of attributes (common for the pointcloud, for instance, center x,y,z)
- save logging in the file format

**Comment by yifatdzigan** [comment]
Summary of [File Formats](http://www.cloudcompare.org/doc/wiki/index.php?title=FILE_I/O), out of which we should focus on: 
**CSV** - ascii
[**PCD** ](http://pointclouds.org/documentation/tutorials/pcd_file_format.php) (used by the [PCL](http://pointclouds.org/)) - ascii/binary,  PCL uses a unique file format to write a PC incl attributes (Colors (RGB), normals, scalar fields)
[**PLY** ](https://en.wikipedia.org/wiki/PLY_(file_format))- ascii/binary, a format for storing graphical objects that are described as a collection of polygons. 
[**BIN** ](http://www.cloudcompare.org/doc/wiki/index.php?title=BIN)(used by [cloud compare](http://www.cloudcompare.org/doc/wiki/index.php?title=Main_Page)) -binary, C++, less favorable

**Comment by yifatdzigan** [comment]
PLY file format can be expended with unlimited number of attributes (features, classes) and the "comment" line in the header can contain a log (to document steps in the work flow that can change from one classification to the other).
CloudCompare can handle PLY and can run on Windows, MacOS and Linux.
