### ISSUE TITLE
Normal vector feature extraction [4]

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#35]
ask Zsofi for the exact explanation

1. fit a plane (robustly, with least squares fitting?) to the selected points within the neighborhood (within cylinder), 
2. from the fitted plane equation: nx,ny,nz can be extracted

All feature extractors need to implement the feature extractor interface from #19.
This feature is similar to: #22, #20

**Comment by komazsofi** [comment]
![](https://github.com/eEcoLiDAR/ecolidar_knowledgebase/blob/master/Figures/Screenshot%20from%202017-09-04%2015-40-00.png?raw=true)

**Comment by cwmeijer** [comment]
Note that I just wrote a plane fitting function. Check https://github.com/eEcoLiDAR/eEcoLiDAR/commit/e9323f31fcfe2c18460bf67a1d5f235ce800ab3a
It's in a another feature branch still (feature-issue20-sigmaz).
