### ISSUE TITLE
Create file loading module

### ISSUE THREAD

**Issue by cwmeijer** [eEcoLiDAR/eEcoLiDAR#4]
Module should load LAS files or LAZ files. One of the two is good enough for now but preferably both.

**Comment by yifatdzigan** [comment]
NumPy-based text/binary PLY file reader/writer for Python: https://github.com/dranjan/python-plyfile.

**Comment by yifatdzigan** [comment]
Add/test write_ply.py

**Comment by elboyran** [comment]
The `read_las` creates a point cloud with x,y and z being doubles, while the ply writer uses float.
