### ISSUE TITLE
How can I identify that within the development branch which version I am testing?

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#83]
It has some code identifier which I can include in my python script to know which version of laserchicken was used in the script?

**Comment by cwmeijer** [comment]
no not yet. when we are close to a version that is good enough to do experiments with (for the paper), we will make a release 0.1.0. From then on, we will keep track of the version. I think it's a bit too early right now to add version administration. All versions are called 0.1.0 for now.
