### ISSUE TITLE
Feature extraction 

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#85]
````
from laserchicken import read_las
from laserchicken import write_ply
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken.compute_neighbors import compute_neighborhoods
from laserchicken.volume_specification import Sphere, InfiniteCylinder
from laserchicken.feature_extractor import compute_features

import numpy as np

# Import
pc = read_las.read("D:/Wetland/GEOBIA/Data/AHN2/12en1_sel2_ground_height_clipped.las")

# Neighborhood calculation

indices_cyl=compute_neighborhoods(pc, pc, InfiniteCylinder(2))

for i in range(len(indices_cyl)):
    features=compute_features(pc, indices_cyl, pc, ['kurto_z'], InfiniteCylinder(2))
    print(features)
````

error message:
Traceback (most recent call last):
  File "D:/GitHub/komazsofi/myPhD_escience_analysis/test_laserchicken/test_GEOBIA_vxxxx.py", line 19, in <module>
    features=compute_features(pc, indices_cyl, pc, ['kurto_z'], InfiniteCylinder(2))
  File "D:\GitHub\eEcoLiDAR\develop-branch\eEcoLiDAR\laserchicken\feature_extractor\__init__.py", line 40, in compute_features
    ordered_features = _make_feature_list(feature_names)
  File "D:\GitHub\eEcoLiDAR\develop-branch\eEcoLiDAR\laserchicken\feature_extractor\__init__.py", line 71, in _make_feature_list
    feature_list = reversed(_make_feature_list_helper(feature_names))
  File "D:\GitHub\eEcoLiDAR\develop-branch\eEcoLiDAR\laserchicken\feature_extractor\__init__.py", line 79, in _make_feature_list_helper
    extractor = FEATURES[feature_name]()
KeyError: 'kurto_z'

if you are try to call 'sigma_z' the program is running however all the result is None.

**Comment by cwmeijer** [comment]
Added some code documentation, better exceptions and also fixed the bug. The feature you were trying to use was complete but not yet imported in the right module. It was therefore still unavailable. I fixed that.

**Comment by komazsofi** [comment]
Still, every single value what is returning from the feature calculation is None. However, If I simply use numpy I got back the right results. 

```python
from laserchicken import read_las
from laserchicken import write_ply
from laserchicken.keys import point
from laserchicken.spatial_selections import points_in_polygon_wkt
from laserchicken.compute_neighbors import compute_neighborhoods
from laserchicken.volume_specification import Sphere, InfiniteCylinder
from laserchicken.feature_extractor import compute_features

import numpy as np
import time

# Import
pc = read_las.read("D:/NAEM/Data/ALS_AHN2/SelStudyArea2_v2.las")
pc_sub = points_in_polygon_wkt(pc, "POLYGON((196550 446510,196550 446540,196580 446540,196580 446510,196550 446510))")

# Neighborhood calculation

start = time.time()
indices_cyl=compute_neighborhoods(pc_sub, pc_sub, InfiniteCylinder(5))
end = time.time()
difftime=end - start
print(("build kd-tree: %f sec") % (difftime))

output_text1 = ""
start1 = time.time()
for i in range(len(indices_cyl)):
    features=compute_features(pc_sub, indices_cyl, pc_sub, ['max_z'], InfiniteCylinder(5))

    output_text1 += "%s,%s,%s,%s\n" % (
    pc_sub[point]['x']['data'][i], pc_sub[point]['y']['data'][i], pc_sub[point]['z']['data'][i],features)

end1 = time.time()
difftime1=end1 - start1
print(("New laserchicken version calculation of max z took: %f sec") % (difftime1))

fileout = open('D:/GitHub/komazsofi/myPhD_escience_analysis/test_data/SelStudyArea2_withfea.txt', "w")
fileout.write(output_text1)
fileout.close()

output_text2 = ""
start2 = time.time()
for i in range(len(indices_cyl)):
    max_z=np.max(pc_sub[point]['z']['data'][indices_cyl[i]])
    output_text2 += "%s,%s,%s,%s\n" % (
    pc_sub[point]['x']['data'][i], pc_sub[point]['y']['data'][i], pc_sub[point]['z']['data'][i],max_z)
end2 = time.time()
difftime2=end2 - start2
print(("Simple calculation of max z took: %f sec") % (difftime2))

fileout = open('D:/GitHub/komazsofi/myPhD_escience_analysis/test_data/SelStudyArea2_withfea2.txt', "w")
fileout.write(output_text2)
fileout.close()
```

**Comment by cwmeijer** [comment]
This is something that is described in the documentation now. The function doesn't return anything (hence it becomes None). It however adds the values to new point attributes in your target point cloud.
So to do what you want in your code, you should change this line:
```
features=compute_features(pc_sub, indices_cyl, pc_sub, ['max_z'], InfiniteCylinder(5))
```
to:
```
compute_features(pc_sub, indices_cyl, pc_sub, ['max_z'], InfiniteCylinder(5))
features = pc_sub[point]['max_z']['data']
```

**Comment by komazsofi** [comment]
It's working! Just one question: where this compute_feature function is located (in which .py file)?

**Comment by cwmeijer** [comment]
https://github.com/eEcoLiDAR/eEcoLiDAR/blob/development/laserchicken/feature_extractor/__init__.py

Make sure your IDE can find, and shows you the function documentation while you're programming. I'll help you configuring PyCharm next Wednesday if necessary.
