### ISSUE TITLE
Eigenvalue calculation error

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#93]
If I do not have enough point for eigenvalue calculation the whole program stops. Maybe we should introduce a filter and write NaN into the attribute column and run the other feature calculation?

error message:

D:/Koma/GitHub/eEcoLiDAR\laserchicken\utils.py:131: FutureWarning: rcond parameter will change to the default of machine precision times max(M, N) where M and N are the input matrix dimensions. To use the future default and silence this warning we advise to pass rcond=None, to keep using the old, explicitly pass rcond=-1. parameters, _, , _ = np.linalg.lstsq(matrix, a) Traceback (most recent call last): File "D:/Koma/GitHub/myPhD_escience_analysis/test_laserchicken/computefea_geobia.py", line 32, in 'eigenv_1','eigenv_2','eigenv_3','sigma_z','perc_20','perc_40','perc_60','perc_80'], Sphere(2.5)) File "D:/Koma/GitHub/eEcoLiDAR\laserchicken\feature_extractor_init.py", line 58, in compute_features add_or_update_feature(env_point_cloud, neighborhoods, target_point_cloud, extractor, volume, overwrite, kwargs) File "D:/Koma/GitHub/eEcoLiDAR\laserchicken\feature_extractor_init.py", line 78, in _add_or_update_feature target_index, volume) File "D:/Koma/GitHub/eEcoLiDAR\laserchicken\feature_extractor\eigenvals_feature_extractor.py", line 46, in extract eigenvals, eigenvecs = _structure_tensor(matrix) File "D:/Koma/GitHub/eEcoLiDAR\laserchicken\feature_extractor\eigenvals_feature_extractor.py", line 31, in _structure_tensor raise ValueError('Not enough points to compute eigenvalues/vectors.') ValueError: Not enough points to compute eigenvalues/vectors.

**Comment by cwmeijer** [comment]
I propose to make all eigen values 0 in the case there are too few points to calculate the actual eigen values. This is a value you can still track down if you like (because 0 is an impossible value) but at the same time it won't break the rest of the software. If we would assign NaN in such a case instead we would have to take into account the possibility for NaNs everywhere in the system.
