### ISSUE TITLE
Missing points from the result file "Where the points are gone?"

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#97]
Principle problem is the following (calculated feature in this example coefficient of variation but it can be observed on all of the results): 

original point cloud: 
![origpc](https://user-images.githubusercontent.com/24636311/37588867-d2f9c9d2-2b63-11e8-93e7-50c6f84a0a40.PNG)
processed point cloud (target is every point) black ones are gone: 
![resultfea](https://user-images.githubusercontent.com/24636311/37588871-d52c1da4-2b63-11e8-9e57-063da776ac17.PNG)

This was created by using my workflow script: https://github.com/eEcoLiDAR/myPhD_escience_analysis/blob/master/bash_process/laserchicken_run.sh

**Comment by cwmeijer** [comment]
I don't see any specific points that are missing. To me it looks like all black points present in the first image are present in the second image with some colors added to them.

Could you explain some more what is missing exactly?

**Comment by komazsofi** [comment]
The original point cloud is black. The point cloud with color what is remaining from the original point cloud, so the black points are missing and completely vanished after the export. 

Here is the resulted file without in the background of black points:
![resultfea2](https://user-images.githubusercontent.com/24636311/37654783-985f79b2-2c43-11e8-9232-33219e8fd1fa.PNG)

Original point cloud contains 183.573 points after the feature calculation it only remains150.516 points.

**Comment by komazsofi** [comment]
Seems to be that is error of my export (convert values into dataframe and export as csv file)
